FROM php:7.4-fpm-alpine

RUN apk add --no-cache shadow openssl bash mysql-client nodejs npm
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www
RUN rm -rf /var/www/html
RUN ln -s public html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www

RUN composer install \
    && php artisan config:cache \
    && chmod -R 775 storage

EXPOSE 9000

ENTRYPOINT ["php-fpm"]
