version: '3'

networks:
    app_network:
      driver: bridge

services:
    fullcycle_app:
        build: .docker/cloudbuild
        container_name: fullcycle_app
        volumes:
          - .:/var/www
        networks:
          - app_network
        depends_on:
            - fullcycle_db
            - fullcycle_redis

    fullcycle_nginx:
        build: .docker/nginx
        container_name: fullcycle_nginx
        working_dir: /var/www
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -timeout 10s ./.docker/nginx/entrypoint.sh
        environment:
          - NGINX_HOST=fullcycle_app
          - NGINX_PORT=9000
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
        networks:
          - app_network
        depends_on:
            - fullcycle_app

    fullcycle_db:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: fullcycle_db
        restart: always
        tty: true
        ports:
          - "3306:3306"
        volumes:
          - ./.docker/dbdata:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=fullcycle_db
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=root
        networks:
          - app_network

    fullcycle_redis:
        image: redis:alpine
        container_name: fullcycle_redis
        expose:
          - 6379
        networks:
          - app_network


