apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
#Spec do deployment
spec: 
  #Selector parar criar um novo service
  selector:
    matchLabels:
      app: redis
  replicas: 1
  #Configuração para os pods
  template:
    metadata:
      labels:
        app: redis
        role: master

    #Specs de pods
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
    role: master
spec:
  selector:
    app: redis
    role: master
  ports:
  - port: 6379
    targetPort: 6379