apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    #replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.17-alpine
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: /etc/nginx/conf.d
                readOnly: true
                name: nginx-conf
            volumes:
            - name: nginx-conf
              configMap:
                name: nginx-conf
                items:
                  - key: nginx.conf
                    path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80