apiVersion: apps/v1
kind: Deployment
metadata:
    name: app
spec:
    #replicas: 3
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
            - name: app
              image: img-app-deployment
              command: ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx; php-fpm;"]
              ports:
              - containerPort: 80
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-pass
                      key: password
              envFrom:
              - configMapRef:
                  name: app-conf
              volumeMounts:
              - name: app-conf
                mountPath: /var/www/.env
                subPath: .env
                readOnly: true
            volumes:
            - name: app-conf
              configMap:
                name: app-conf
                items:
                  - key: env
                    path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 9000
    protocol: TCP
    nodePort: 30080